# Generated by Django 3.1.7 on 2021-03-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210322_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
    ]
