# Generated by Django 3.1.7 on 2021-03-22 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_post_item_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Sell',
        ),
    ]
