# Generated by Django 3.1.7 on 2021-03-22 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20210322_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sell',
            new_name='Items',
        ),
    ]
