# Generated by Django 3.1.7 on 2021-03-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210322_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_type',
            field=models.CharField(choices=[('DRAFTERS', 'Drafters'), ('BOOKS', 'Books'), ('CYCLES', 'Cycles'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
