# Generated by Django 3.1.7 on 2021-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210329_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemscart',
            name='item_id',
            field=models.IntegerField(),
        ),
    ]
